## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
urlDB: jdbc:mysql://db4free.net:3307/rafadb?useSSL=false
userDB: rafapc
passDB: nohay2sin4815162342
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2
##passDB: clasesdaw